FROM underworldcode/uw_user_cloud:2019.07.07_dev

## =============================================================
## base - image ... whatever functionality you want to provide !
## This is my unix / python stuff (but it doesn't have underworld)
##
## This dockerfile builds an image from this content, and serves the
## sample web pages and notebooks at port 8080
##
## docker run -p 8181:8080 --name="docker-web-notebooks-test" -t lmoresi/lmoresi/docker-web-notebooks-module
## and then browse the docker VM ip address on port 8181 (for example)
##
## OR just use kitematic and click on the preview image
##
## =============================================================

USER root

RUN pip install git+https://github.com/underworldcode/stripy
RUN pip install lavavu --upgrade
# RUN pip install  git+https://github.com/jmansour/underworld2@pip


RUN apt-get update && apt-get install -y \
  libproj-dev \
  gdal-bin \
  libgdal-dev \
  python3-gdal

RUN pip install cartopy
RUN pip install imageio

ENV JUPYTERLAB_DIR=/user_data/jupyterlab

RUN jupyter-labextension enable @jupyterlab/git
RUN jupyter-labextension enable @jupyterlab/github
RUN jupyter-labextension enable @jupyterlab/google-drive
RUN jupyter-serverextension enable --py jupyterlab_git

ADD --chown=jovyan:jovyan  0_Intro2Python  Intro2Python
ADD --chown=jovyan:jovyan  1_UserContent   .UserContent
ADD --chown=jovyan:jovyan  Docker/Kub-JHub/install_user_files.py scripts/install_user_files.py
ADD --chown=jovyan:jovyan  Docker/Kub-JHub/@jupyterlab  configs/@jupyterlab

# This kills the markdown (etc) editor but allows it to be reenabled from the running terminal
RUN jupyter-labextension disable @jupyterlab/fileeditor-extension
RUN chmod -R a+rw /user_data/jupyterlab

USER jovyan

# This ensures that the notebooks can run in a stand-alone container
# In the normal way this will be nuked by the hub mount of /home/jovyan

RUN mkdir -p /home/jovyan/
RUN mkdir -p /home/jovyan/.jupyter/lab/user-settings
RUN mkdir -p /home/jovyan/Intro2Python
RUN ln -s /user_data/configs/@jupyterlab /home/jovyan/.jupyter/lab/user-settings/@jupyterlab
RUN ln -s /home/jovyan/Intro2Python /user_data/Intro2Python/MyFiles

WORKDIR  /user_data/Intro2Python


# note we use xvfb which to mimic the X display for lavavu
# ENTRYPOINT ["/usr/local/bin/xvfbrun.sh"]

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--NotebookApp.token=''", "--LabApp.default_url='/lab/tree/LandingPage.md'" ]
