FROM lmoresi/docker-vieps-pye:2019.3

#
# ENV NB_USER jovyan
# ENV NB_UID 1000
# ENV HOME /home/${NB_USER}
# ENV PATH ${HOME}:$PATH
#
# ADD CourseContent/Notebooks Notebooks
# ADD Docker/jupyter_notebook_config-binder.py .jupyter/jupyter_notebook_config.py
#
# USER root
#
# WORKDIR ${HOME}
# RUN chown -R ${NB_UID} ${HOME}
# RUN chown -R ${NB_UID} /tmp
#
# RUN jupyter notebook --version
#
# USER ${NB_USER}

# expose notebook port and server port
# EXPOSE 8888

# note we use xvfb which to mimic the X display for lavavu
# ENTRYPOINT ["jupyter", "lab","--ip=0.0.0.0","--allow-root", "--NotebookApp.token=''"]
