FROM lmoresi/docker-vieps-pye:2019.1

ADD --chown=jovyan:jovyan Docker/jupyter_notebook_config-binder.py .jupyter/jupyter_notebook_config.py

# expose notebook port and server port
# EXPOSE 8888

# note we use xvfb which to mimic the X display for lavavu
# ENTRYPOINT ["jupyter", "lab","--ip=0.0.0.0","--allow-root", "--NotebookApp.token=''"]
