#!/bin/sh
#

set -e
cd $(dirname "$0")/..

# One shot build in cwd

bundle exec jekyll build
bundle exec compass compile
bundle exec jekyll build

# Now symlink Notebooks from the original location

cd _site/Content && ln -s ../../Content/Notebooks/ Notebooks
