#!/bin/sh

# Builds and watches the current directory
# Starts a web server at the _site directory

set -e
cd $(dirname "$0")/..

# Let these run in case we add content via the externally mounted VOLUME

# Now that we have  symlink to the original content, we have to be careful that the
# build scripts don't clean the _site directory when we are not expecting it. 

# bundle exec jekyll build --watch &
# bundle exec compass watch &

# This is the notebook server

# We want to start the server from the _site directory
# where everything is being built by the above commands.

cd _site

jupyter notebook --port=8080 --ip=0.0.0.0 --no-browser --NotebookApp.default_url="/files/Content/index.html"
# --NotebookApp.file_to_run="_site/index.html"
