#!/bin/sh
#
# Usage:
#   _scripts/livebuilder

cd /demonstration

# Let these run in case we add content via the externally mounted VOLUME

bundle exec jekyll build --watch &
bundle exec compass watch &

# This is the notebook server
jupyter notebook --port=8080 --no-browser --NotebookApp.default_url="/files/index.html" --NotebookApp.file_to_run="_site/index.html"
