#!/bin/sh


# Let these run in case we add content via the externally mounted VOLUME

bundle exec jekyll build --watch &
bundle exec compass watch &

# This is the notebook server

# We want to start the server from the _site directory
# where everything is being built
# by the above commands.

cd _site

jupyter notebook --port=8080 --ip=0.0.0.0 --no-browser --NotebookApp.default_url="/files/Content/index.html"
# --NotebookApp.file_to_run="_site/index.html"
