#!/bin/sh

# Builds and watches the current directory
# Starts a web server at the _site directory

# choose some default value that won't cause trouble.
# Set the -p #### flag to over-ride it

port=8899

options=':p::h'

while getopts $options option
do
    case $option in
        p  )    port=$OPTARG
                echo "port: " $OPTARG;;
        h  )    echo "run-jupyter -p PORT" ;;
        \? )    echo "Unknown option: -$OPTARG" ;;
        * )     exit "Missing option argument: -$OPTARG"
                exit -1 ;;
    esac
done

set -e
cd $(dirname "$0")/..

# We want to start the server from the _site directory
# where everything was built by the docker-site-builder script

jupyter notebook --port=$port --ip=0.0.0.0 --no-browser --NotebookApp.default_url="/files/www/index.html"
